services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password1
      POSTGRES_USER: admin
      POSTGRES_DB: admin
    ports:
      - "6500:5432"
    volumes:
      - progresDB:/var/lib/postgresql/data
    restart: always

  interface:
    build:
      context: ./interface
    ports:
      - "3000:3000"
    volumes:
      - ./interface:/usr/src/interface  # Mounts local code as a volume for hot-reload
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  progresDB:
